import React, { useEffect, useState } from "react";

import {
  createLead,
  updateLead,
  getMyLeads,
  type LeadInput,
  type LeadRecord,
} from "../lib/leadService";

import { useAuthStore } from "../store/authStore";

const LeadManagement: React.FC = () => {
  const { user, profile } = useAuthStore() as any;

  const [leads, setLeads] = useState<LeadRecord[]>([]);
  const [loading, setLoading] = useState(false);

  const loadLeads = async () => {
    try {
      setLoading(true);
      const data = await getMyLeads();
      setLeads(data);
    } catch (err) {
      console.error("Failed to load leads:", err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadLeads();
  }, []);

  // CREATE LEAD
  const handleCreateLead = async (form: LeadInput) => {
    try {
      setLoading(true);
      const newLead = await createLead(form);
      setLeads((prev) => [newLead, ...prev]);
    } catch (err) {
      console.error("Create Lead Error:", err);
      alert("Could not create lead.");
    } finally {
      setLoading(false);
    }
  };

  // UPDATE LEAD
  const handleUpdateLead = async (id: string, updates: Partial<LeadInput>) => {
    try {
      setLoading(true);
      const updated = await updateLead(id, updates);
      setLeads((prev) => prev.map((l) => (l.id === id ? updated : l)));
    } catch (err) {
      console.error("Update Lead Error:", err);
      alert("Could not update lead.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div>
      <h1 className="text-2xl font-semibold mb-4">Lead Management</h1>

      {/* Example UI — Replace with your own modals/forms */}
      <button
        className="px-4 py-2 bg-blue-600 text-white rounded"
        onClick={() =>
          handleCreateLead({
            name: "New Lead",
            notes: "Generated by test",
          })
        }
      >
        Test Create Lead
      </button>

      <div className="mt-6 space-y-3">
        {leads.map((lead) => (
          <div
            key={lead.id}
            className="border rounded p-4 bg-white shadow-sm flex justify-between items-center"
          >
            <div>
              <div className="font-medium">{lead.name}</div>
              <div className="text-gray-600 text-sm">
                Status: {lead.status}
              </div>
            </div>

            <button
              className="text-blue-600"
              onClick={() =>
                handleUpdateLead(lead.id, {
                  status: "contacted",
                })
              }
            >
              Mark Contacted
            </button>
          </div>
        ))}
      </div>
    </div>
  );
};

export default LeadManagement;
