import React from 'react';
import { AlertCircle, Link as LinkIcon } from 'lucide-react';
import { useAuthStore } from '../store/authStore';
import { useDataStore } from '../store/dataStore';

const ProspectsManager: React.FC = () => {
  const { profile } = useAuthStore();
  const { affiliateDashboard } = useDataStore();

  return (
    <div className="space-y-5">
      <div className="bg-gradient-to-br from-red-50 to-orange-50 rounded-xl p-5 shadow-sm border border-red-100">
        <div className="flex items-start gap-3">
          <div className="w-12 h-12 bg-red-500 rounded-lg flex items-center justify-center">
            <LinkIcon className="w-6 h-6 text-white" />
          </div>
          <div>
            <h1 className="text-xl font-semibold text-gray-900">Affiliate referrals replace CRM prospects</h1>
            <p className="text-sm text-gray-700 mt-1">
              We have transitioned the prospecting workspace to focus on AffiliateWP referrals and payouts. Use the Affiliate Dashboard to monitor leads generated by your referral link.
            </p>
            <div className="mt-3">
              <code className="inline-flex items-center gap-2 bg-white rounded-md px-3 py-2 text-sm text-gray-700 border border-red-200">
                {profile?.affiliate_referral_url || 'Affiliate account pending creation'}
              </code>
            </div>
          </div>
        </div>
      </div>

      <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-6">
        <div className="flex items-start gap-3">
          <AlertCircle className="w-6 h-6 text-amber-500" />
          <div>
            <h2 className="text-lg font-semibold text-gray-900">CRM pipeline has been sunset</h2>
            <p className="text-sm text-gray-600 mt-1">
              We no longer collect or display manual prospect records. All actionable data comes directly from AffiliateWP, including referral events, traffic, and payout readiness. Visit the Affiliate Dashboard or Agency Dashboard for real-time performance analytics.
            </p>
            {affiliateDashboard && (
              <ul className="mt-4 grid gap-2 text-sm text-gray-700">
                <li>
                  <span className="font-semibold text-gray-900">Total referrals:</span>{' '}
                  {affiliateDashboard.overview.referrals.toLocaleString()}
                </li>
                <li>
                  <span className="font-semibold text-gray-900">Pending payouts:</span>{' '}
                  {`$${affiliateDashboard.overview.unpaidEarnings.toLocaleString()}`}
                </li>
                <li>
                  <span className="font-semibold text-gray-900">Visits tracked:</span>{' '}
                  {affiliateDashboard.overview.visits.toLocaleString()}
                </li>
              </ul>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default ProspectsManager;
