/*
  # Complete AffiliateWP Configuration and Schema Enhancement

  1. Schema Updates
    - Add missing columns to `affiliates` table:
      - `tier_level` - Affiliate tier (bronze, silver, gold, platinum, standard)
      - `total_sales` - Total sales generated by affiliate
      - `total_commissions` - Total commissions earned
      - `onboarding_status` - Onboarding workflow status
      - `assigned_manager_id` - Optional manager assignment
      - `notes` - Additional notes about affiliate
    - Set default values for existing columns
    - Add constraints and checks

  2. New Tables
    - `affiliate_rate_history` - Track all commission rate changes with history

  3. Indexes
    - Add indexes for performance on frequently queried columns

  4. Triggers
    - Create trigger to automatically update affiliate performance totals when commissions change

  5. Security
    - Enable RLS on new tables
    - Add policies for authenticated users

  6. Important Notes
    - All existing data is preserved
    - Default values are set for new columns
    - Triggers maintain data consistency automatically
*/

-- Add missing columns to affiliates table
DO $$
BEGIN
  -- Add tier_level column
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'affiliates' AND column_name = 'tier_level'
  ) THEN
    ALTER TABLE public.affiliates ADD COLUMN tier_level text DEFAULT 'standard' CHECK (tier_level IN ('bronze', 'silver', 'gold', 'platinum', 'standard'));
  END IF;

  -- Add total_sales column
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'affiliates' AND column_name = 'total_sales'
  ) THEN
    ALTER TABLE public.affiliates ADD COLUMN total_sales numeric(12,2) DEFAULT 0 NOT NULL;
  END IF;

  -- Add total_commissions column
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'affiliates' AND column_name = 'total_commissions'
  ) THEN
    ALTER TABLE public.affiliates ADD COLUMN total_commissions numeric(12,2) DEFAULT 0 NOT NULL;
  END IF;

  -- Add onboarding_status column
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'affiliates' AND column_name = 'onboarding_status'
  ) THEN
    ALTER TABLE public.affiliates ADD COLUMN onboarding_status text DEFAULT 'pending' CHECK (onboarding_status IN ('pending', 'in_progress', 'completed', 'on_hold'));
  END IF;

  -- Add assigned_manager_id column
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'affiliates' AND column_name = 'assigned_manager_id'
  ) THEN
    ALTER TABLE public.affiliates ADD COLUMN assigned_manager_id uuid;
  END IF;

  -- Add notes column
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'affiliates' AND column_name = 'notes'
  ) THEN
    ALTER TABLE public.affiliates ADD COLUMN notes text;
  END IF;
END $$;

-- Set default values for existing nullable columns
ALTER TABLE public.affiliates ALTER COLUMN status SET DEFAULT 'active';
ALTER TABLE public.affiliates ALTER COLUMN upfront_rate SET DEFAULT 10.00;
ALTER TABLE public.affiliates ALTER COLUMN residual_rate SET DEFAULT 5.00;
ALTER TABLE public.affiliates ALTER COLUMN created_at SET DEFAULT timezone('utc'::text, now());
ALTER TABLE public.affiliates ALTER COLUMN updated_at SET DEFAULT timezone('utc'::text, now());

-- Add constraints to affiliates table
ALTER TABLE public.affiliates DROP CONSTRAINT IF EXISTS affiliates_status_check;
ALTER TABLE public.affiliates ADD CONSTRAINT affiliates_status_check CHECK (status IN ('active', 'inactive', 'suspended'));

ALTER TABLE public.affiliates DROP CONSTRAINT IF EXISTS affiliates_upfront_rate_check;
ALTER TABLE public.affiliates ADD CONSTRAINT affiliates_upfront_rate_check CHECK (upfront_rate >= 0 AND upfront_rate <= 100);

ALTER TABLE public.affiliates DROP CONSTRAINT IF EXISTS affiliates_residual_rate_check;
ALTER TABLE public.affiliates ADD CONSTRAINT affiliates_residual_rate_check CHECK (residual_rate >= 0 AND residual_rate <= 100);

-- Create affiliate_rate_history table
CREATE TABLE IF NOT EXISTS public.affiliate_rate_history (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    affiliate_id uuid NOT NULL REFERENCES public.affiliates(id) ON DELETE CASCADE,
    previous_upfront_rate numeric(5,2),
    new_upfront_rate numeric(5,2) NOT NULL,
    previous_residual_rate numeric(5,2),
    new_residual_rate numeric(5,2) NOT NULL,
    reason text,
    changed_by uuid REFERENCES auth.users(id),
    effective_date timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on affiliate_rate_history
ALTER TABLE public.affiliate_rate_history ENABLE ROW LEVEL SECURITY;

-- Create RLS policies for affiliate_rate_history
CREATE POLICY "Enable read access for authenticated users" 
ON public.affiliate_rate_history 
FOR SELECT 
TO authenticated
USING (true);

CREATE POLICY "Enable insert for authenticated users" 
ON public.affiliate_rate_history 
FOR INSERT 
TO authenticated
WITH CHECK (true);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_affiliates_tier_level ON public.affiliates(tier_level);
CREATE INDEX IF NOT EXISTS idx_affiliates_status ON public.affiliates(status);
CREATE INDEX IF NOT EXISTS idx_affiliates_onboarding_status ON public.affiliates(onboarding_status);
CREATE INDEX IF NOT EXISTS idx_affiliates_assigned_manager ON public.affiliates(assigned_manager_id);
CREATE INDEX IF NOT EXISTS idx_affiliate_rate_history_affiliate_id ON public.affiliate_rate_history(affiliate_id);
CREATE INDEX IF NOT EXISTS idx_affiliate_rate_history_effective_date ON public.affiliate_rate_history(effective_date DESC);
CREATE INDEX IF NOT EXISTS idx_commission_entries_affiliate_id ON public.commission_entries(affiliate_id);
CREATE INDEX IF NOT EXISTS idx_commission_entries_status ON public.commission_entries(status);
CREATE INDEX IF NOT EXISTS idx_commission_entries_created_at ON public.commission_entries(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_webhook_logs_processed ON public.webhook_logs(processed);
CREATE INDEX IF NOT EXISTS idx_webhook_logs_created_at ON public.webhook_logs(created_at DESC);

-- Create trigger function to update affiliate performance totals
CREATE OR REPLACE FUNCTION update_affiliate_performance()
RETURNS TRIGGER AS $$
BEGIN
    -- Update affiliate totals when commission entry is inserted or updated
    IF TG_OP = 'INSERT' OR TG_OP = 'UPDATE' THEN
        UPDATE public.affiliates
        SET 
            total_sales = (
                SELECT COALESCE(SUM(order_total), 0)
                FROM public.commission_entries
                WHERE affiliate_id = NEW.affiliate_id
            ),
            total_commissions = (
                SELECT COALESCE(SUM(commission_amount), 0)
                FROM public.commission_entries
                WHERE affiliate_id = NEW.affiliate_id
            ),
            updated_at = timezone('utc'::text, now())
        WHERE id = NEW.affiliate_id;
    END IF;

    -- Update affiliate totals when commission entry is deleted
    IF TG_OP = 'DELETE' THEN
        UPDATE public.affiliates
        SET 
            total_sales = (
                SELECT COALESCE(SUM(order_total), 0)
                FROM public.commission_entries
                WHERE affiliate_id = OLD.affiliate_id
            ),
            total_commissions = (
                SELECT COALESCE(SUM(commission_amount), 0)
                FROM public.commission_entries
                WHERE affiliate_id = OLD.affiliate_id
            ),
            updated_at = timezone('utc'::text, now())
        WHERE id = OLD.affiliate_id;
    END IF;

    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Create trigger to automatically update affiliate performance
DROP TRIGGER IF EXISTS trigger_update_affiliate_performance ON public.commission_entries;
CREATE TRIGGER trigger_update_affiliate_performance
    AFTER INSERT OR UPDATE OR DELETE ON public.commission_entries
    FOR EACH ROW
    EXECUTE FUNCTION update_affiliate_performance();

-- Create trigger function to track affiliate rate changes
CREATE OR REPLACE FUNCTION track_affiliate_rate_changes()
RETURNS TRIGGER AS $$
BEGIN
    -- Only track if rates actually changed
    IF (OLD.upfront_rate IS DISTINCT FROM NEW.upfront_rate) OR 
       (OLD.residual_rate IS DISTINCT FROM NEW.residual_rate) THEN
        
        INSERT INTO public.affiliate_rate_history (
            affiliate_id,
            previous_upfront_rate,
            new_upfront_rate,
            previous_residual_rate,
            new_residual_rate,
            reason,
            changed_by
        ) VALUES (
            NEW.id,
            OLD.upfront_rate,
            NEW.upfront_rate,
            OLD.residual_rate,
            NEW.residual_rate,
            'Rate updated',
            auth.uid()
        );
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Create trigger to automatically track rate changes
DROP TRIGGER IF EXISTS trigger_track_rate_changes ON public.affiliates;
CREATE TRIGGER trigger_track_rate_changes
    AFTER UPDATE ON public.affiliates
    FOR EACH ROW
    WHEN (OLD.upfront_rate IS DISTINCT FROM NEW.upfront_rate OR 
          OLD.residual_rate IS DISTINCT FROM NEW.residual_rate)
    EXECUTE FUNCTION track_affiliate_rate_changes();

-- Create trigger to update affiliates updated_at timestamp
CREATE OR REPLACE FUNCTION update_affiliates_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_affiliates_updated_at_trigger ON public.affiliates;
CREATE TRIGGER update_affiliates_updated_at_trigger
    BEFORE UPDATE ON public.affiliates
    FOR EACH ROW
    EXECUTE FUNCTION update_affiliates_updated_at();

-- Ensure RLS is enabled on all affiliate tables
ALTER TABLE public.affiliates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.commission_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.webhook_logs ENABLE ROW LEVEL SECURITY;

-- Create RLS policies for affiliates table (if not exists)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'affiliates' AND policyname = 'Enable read access for authenticated users'
    ) THEN
        CREATE POLICY "Enable read access for authenticated users" 
        ON public.affiliates 
        FOR SELECT 
        TO authenticated
        USING (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'affiliates' AND policyname = 'Enable insert for authenticated users'
    ) THEN
        CREATE POLICY "Enable insert for authenticated users" 
        ON public.affiliates 
        FOR INSERT 
        TO authenticated
        WITH CHECK (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'affiliates' AND policyname = 'Enable update for authenticated users'
    ) THEN
        CREATE POLICY "Enable update for authenticated users" 
        ON public.affiliates 
        FOR UPDATE 
        TO authenticated
        USING (true)
        WITH CHECK (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'affiliates' AND policyname = 'Enable delete for authenticated users'
    ) THEN
        CREATE POLICY "Enable delete for authenticated users" 
        ON public.affiliates 
        FOR DELETE 
        TO authenticated
        USING (true);
    END IF;
END $$;

-- Create RLS policies for commission_entries table (if not exists)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'commission_entries' AND policyname = 'Enable read access for authenticated users'
    ) THEN
        CREATE POLICY "Enable read access for authenticated users" 
        ON public.commission_entries 
        FOR SELECT 
        TO authenticated
        USING (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'commission_entries' AND policyname = 'Enable insert for authenticated users'
    ) THEN
        CREATE POLICY "Enable insert for authenticated users" 
        ON public.commission_entries 
        FOR INSERT 
        TO authenticated
        WITH CHECK (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'commission_entries' AND policyname = 'Enable update for authenticated users'
    ) THEN
        CREATE POLICY "Enable update for authenticated users" 
        ON public.commission_entries 
        FOR UPDATE 
        TO authenticated
        USING (true)
        WITH CHECK (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'commission_entries' AND policyname = 'Enable delete for authenticated users'
    ) THEN
        CREATE POLICY "Enable delete for authenticated users" 
        ON public.commission_entries 
        FOR DELETE 
        TO authenticated
        USING (true);
    END IF;
END $$;

-- Create RLS policies for webhook_logs table (if not exists)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'webhook_logs' AND policyname = 'Enable read access for authenticated users'
    ) THEN
        CREATE POLICY "Enable read access for authenticated users" 
        ON public.webhook_logs 
        FOR SELECT 
        TO authenticated
        USING (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'webhook_logs' AND policyname = 'Enable insert for service role'
    ) THEN
        CREATE POLICY "Enable insert for service role" 
        ON public.webhook_logs 
        FOR INSERT 
        WITH CHECK (true);
    END IF;
END $$;

-- Update existing affiliates to have default values if needed
UPDATE public.affiliates
SET 
    tier_level = COALESCE(tier_level, 'standard'),
    total_sales = COALESCE(total_sales, 0),
    total_commissions = COALESCE(total_commissions, 0),
    onboarding_status = COALESCE(onboarding_status, 'completed'),
    status = COALESCE(status, 'active'),
    upfront_rate = COALESCE(upfront_rate, 10.00),
    residual_rate = COALESCE(residual_rate, 5.00)
WHERE tier_level IS NULL 
   OR total_sales IS NULL 
   OR total_commissions IS NULL 
   OR onboarding_status IS NULL
   OR status IS NULL
   OR upfront_rate IS NULL
   OR residual_rate IS NULL;